services:
  - type: web
    name: kassahun-backend
    runtime: node
    plan: free
    buildCommand: pnpm install && pnpm build && pnpm drizzle-kit push && pnpm db:seed:super-admin
    startCommand: node dist/src/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: '587'
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: MAIL_FROM
        value: noreply@kassahun.com
      - key: FRONTEND_URL
        sync: false
      - key: CORS_ORIGIN
        sync: false
    healthCheckPath: /api/v1/health
